In [5]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time
import os
import pandas as pd 
from io import StringIO
import numpy as np
from bs4 import BeautifulSoup

In [21]:
import os
os.listdir()

['scrap_nba.ipynb']

In [22]:
chromedriver_path = r"C:\Users\isafo\Desktop\Proyecto\chromedriver.exe"

In [25]:
import os

os.path.exists(r"C:\Users\isafo\Desktop\Proyecto\chromedriver.exe")

False

In [27]:
import os

os.listdir(r"C:\Users\isafo\Desktop\LIDIA MANTILLA\Maestria Ciberseguridad\Tratamiento de datos")

['.git',
 '.vscode',
 'analisis_datos',
 'Hello World',
 'microservicio',
 'Proyecto',
 'scrap_nba.ipynb',
 'venv',
 'web_scrapping']

In [29]:
chromedriver_path = r"C:\Users\isafo\Desktop\Proyecto\chromedriver-win64\chromedriver.exe"

In [91]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

chromedriver_path = r"C:\Users\isafo\Desktop\LIDIA MANTILLA\Maestria Ciberseguridad\Tratamiento de datos\chromedriver.exe"

service = Service(chromedriver_path)

driver = webdriver.Chrome(service=service)

NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

In [87]:
import os

ruta = r"C:\Users\isafo\Desktop\LIDIA MANTILLA\Maestria Ciberseguridad\Tratamiento de datos\chromedriver.exe"
print(os.path.exists(ruta))

False

In [88]:
os.listdir(r"C:\Users\isafo\Desktop\LIDIA MANTILLA\Maestria Ciberseguridad\Tratamiento de datos")

['.git',
 '.vscode',
 'analisis_datos',
 'Hello World',
 'microservicio',
 'Proyecto',
 'scrap_nba.ipynb',
 'venv',
 'web_scrapping']

In [89]:
from selenium import webdriver

# Selenium encuentra automáticamente el driver de Chrome
driver = webdriver.Chrome()

In [92]:

# Path to chromedriver executable
chromedriver_path = "chromedriver.exe"

# Initialize ChromeDriver with Selenium
service = Service(chromedriver_path)
driver = webdriver.Chrome(service=service)

NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

In [93]:
data_dir = "data"
standings_dir = os.path.join(data_dir, "standings")
scores_dir = os.path.join(data_dir, "scores")

In [94]:
def get_html(url, selector, sleep_time=5):
    driver.get(url)
    time.sleep(sleep_time)
    element = driver.find_element(By.CSS_SELECTOR, selector)

    html_content = element.get_attribute("outerHTML")

    return html_content

In [95]:

# List of seasons
seasons = [2025]

# Iterate over seasons
for season in seasons:
    # Construct URL
    url = f"https://www.basketball-reference.com/leagues/NBA_{season}_games.html"
    
    # Get the HTML content
    driver.get(url)
    
    # Wait for the page to load completely (adjust wait time as needed)
    time.sleep(5)
    
    # Find the element with the specified selector
    element = driver.find_element(By.CSS_SELECTOR, "#content .filter")
    
    # Extract HTML content of the element
    html_content = element.get_attribute("outerHTML")
    
    # Print HTML content
    print(f"HTML content for season {season} with selector '#content .filter':")
    print(html_content)
    print("="*50)

# Quit the driver
# driver.quit()

HTML content for season 2025 with selector '#content .filter':
<div class="filter">

<div class=" current">
	<a href="/leagues/NBA_2025_games-october.html">October</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-november.html">November</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-december.html">December</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-january.html">January</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-february.html">February</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-march.html">March</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-april.html">April</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-may.html">May</a>
</div><div class="">
	<a href="/leagues/NBA_2025_games-june.html">June</a>
</div></div>
==================================================

In [96]:
soup = BeautifulSoup(html_content)
links = soup.find_all("a")

In [97]:
links

[<a href="/leagues/NBA_2025_games-october.html">October</a>,
 <a href="/leagues/NBA_2025_games-november.html">November</a>,
 <a href="/leagues/NBA_2025_games-december.html">December</a>,
 <a href="/leagues/NBA_2025_games-january.html">January</a>,
 <a href="/leagues/NBA_2025_games-february.html">February</a>,
 <a href="/leagues/NBA_2025_games-march.html">March</a>,
 <a href="/leagues/NBA_2025_games-april.html">April</a>,
 <a href="/leagues/NBA_2025_games-may.html">May</a>,
 <a href="/leagues/NBA_2025_games-june.html">June</a>]

In [98]:
standings_pages = [f"https://www.basketball-reference.com{l['href']}" for l in links]

In [99]:
standings_pages

['https://www.basketball-reference.com/leagues/NBA_2025_games-october.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-november.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-december.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-january.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-february.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-march.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-april.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-may.html',
 'https://www.basketball-reference.com/leagues/NBA_2025_games-june.html']

In [100]:
import os

# Asegúrate de que la carpeta exista
os.makedirs(standings_dir, exist_ok=True)

for url in standings_pages:
    save_path = os.path.join(standings_dir, url.split("/")[-1])
    
    if os.path.exists(save_path):
        continue
    
    # Ahora la carpeta existe, podemos abrir el archivo
    with open(save_path, "w+", encoding="utf-8") as f:
        f.write(html_content)

In [101]:
for url in standings_pages:
    save_path = os.path.join(standings_dir, url.split("/")[-1])
    if os.path.exists(save_path):
        continue

    with open(save_path, "w+") as f:
        f.write(html_content)

In [102]:
save_path

'data\\standings\\NBA_2025_games-june.html'

In [103]:
for url in standings_pages:
    save_path = os.path.join(standings_dir, url.split("/")[-1])
    if os.path.exists(save_path):
    
        driver.get(url)
        
        time.sleep(20)
        
        element = driver.find_element(By.CSS_SELECTOR, "#all_schedule")
        
        html_content = element.get_attribute("outerHTML")
        
        with open(save_path, "w+") as f:
            f.write(html_content)

In [104]:
standings_files = os.listdir(standings_dir)

In [106]:
for standings_file in standings_files:
    filepath = os.path.join(standings_dir, standings_file)
    with open(filepath, 'r') as f:  
        html = f.read()

    soup = BeautifulSoup(html)
    links = soup.find_all("a")
    hrefs = [l.get('href') for l in links]
    box_scores = [f"https://www.basketball-reference.com{l}" for l in hrefs if l and "boxscore" in l and '.html' in l]

    for url in box_scores:
        save_path = os.path.join(scores_dir, url.split("/")[-1])
        if os.path.exists(save_path):
            continue
        driver.get(url)
        print('Fetching Data')
        
        time.sleep(30)
        
        element = driver.find_element(By.CSS_SELECTOR, "#content")
        
        html_content = element.get_attribute("outerHTML")
        
        if not html_content:
            continue
        with open(save_path, "w+", encoding="utf-8") as f:
            f.write(html_content)

Fetching Data

FileNotFoundError: [Errno 2] No such file or directory: 'data\\scores\\202504010ATL.html'

In [55]:
box_scores = os.listdir(scores_dir)
box_scores = [os.path.join(scores_dir, f) for f in box_scores if f.endswith(".html")]

FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'data\\scores'

In [56]:
directory = 'data/scores'

# List all files in the directory
files = os.listdir(directory)

# Filter HTML files
html_files = [file for file in files if file.endswith('.html')]

# Check if each HTML file is empty
empty_html_files = []
for file in html_files:
    file_path = os.path.join(directory, file)
    if os.path.getsize(file_path) == 0:
        empty_html_files.append(file)

# Print empty HTML files
print("Empty HTML files:")
for file in empty_html_files:
    print(file)

FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'data/scores'

In [57]:
len(box_scores)

192

In [58]:
def parse_html(box_score):
    with open(box_score, encoding="utf-8") as f:
        html = f.read()

    soup = BeautifulSoup(html)
    [s.decompose() for s in soup.select("tr.over_header")]
    [s.decompose() for s in soup.select("tr.thead")]
    return soup

In [59]:
def read_season_info(soup):
    nav = soup.select("#bottom_nav_container")[0]
    hrefs = [a["href"] for a in nav.find_all('a')]
    season = os.path.basename(hrefs[1]).split("_")[0]
    return season

In [60]:
def read_line_score(soup):
    line_score = pd.read_html(StringIO(str(soup)), attrs = {'id': 'line_score'})[0]

    score_divs = soup.find_all('div', string=True)
    scores = [div.text.strip() for div in score_divs if '-' in div.text]
    win_loss = [(int(score.split('-')[0]), int(score.split('-')[1])) for score in scores]
    df = pd.DataFrame(win_loss, columns=['W', 'L'])
    
    cols = list(line_score.columns)
    cols[0] = "team"
    cols[-1] = "total"
    cols[1] = 'Q1'
    cols[2] = 'Q2'
    cols[3] = 'Q3'
    cols[4] = 'Q4'
    line_score.columns = cols

    line_score = line_score[["team", "total", "Q1", "Q2", "Q3", "Q4"]]

    
    return pd.concat([line_score, df], axis=1)

In [61]:
def read_stats(soup, team, stat):
    df = pd.read_html(StringIO(str(soup)), attrs = {'id': f'box-{team}-game-{stat}'}, index_col=0)[0]
    df = df.apply(pd.to_numeric, errors="coerce")
    return df

In [62]:
def read_player_stats(soup, team, stat):
    df = pd.read_html(StringIO(str(soup)), attrs = {'id': f'box-{team}-game-{stat}'}, index_col=0)[0]
    return df

In [63]:
games = []
base_cols = None
i = 0
for box_score in box_scores:
    try:
        soup = parse_html(box_score)

        line_score = read_line_score(soup)
        teams = list(line_score["team"])

        summaries = []
        for team in teams:
            basic = read_stats(soup, team, "basic")
            advanced = read_stats(soup, team, "advanced")

            totals = pd.concat([basic.iloc[-1,:], advanced.iloc[-1,:]])
            totals.index = totals.index.str.lower()

            maxes = pd.concat([basic.iloc[:-1].max(), advanced.iloc[:-1].max()])
            maxes.index = maxes.index.str.lower() + "_max"

            summary = pd.concat([totals, maxes])
            
            if base_cols is None:
                base_cols = list(summary.index.drop_duplicates(keep="first"))
                base_cols = [b for b in base_cols if "bpm" not in b]
            
            summary = summary[base_cols]
            
            summaries.append(summary)
        summary = pd.concat(summaries, axis=1).T

        game = pd.concat([summary, line_score], axis=1)

        game["home"] = [0,1]

        game_opp = game.iloc[::-1].reset_index()
        game_opp.columns += "_opp"

        full_game = pd.concat([game, game_opp], axis=1)
        full_game["season"] = read_season_info(soup)
        
        full_game["date"] = os.path.basename(box_score)[:8]
        full_game["date"] = pd.to_datetime(full_game["date"], format="%Y%m%d")
        
        full_game["won"] = full_game["total"] > full_game["total_opp"]
        full_game['match_id'] = i
        i += 1
        games.append(full_game)
        
        if len(games) % 100 == 0:
            print(f"{len(games)} / {len(box_scores)}")
    except:
        continue

In [67]:
print(games)
print(len(games))

[]
0

In [68]:
import pandas as pd

# Verifica que haya DataFrames
if games:  # True si la lista no está vacía
    games_df = pd.concat(games, ignore_index=True)
else:
    games_df = pd.DataFrame()  # Crea DataFrame vacío
    print("Warning: No hay juegos para concatenar")

Warning: No hay juegos para concatenar

In [74]:
import os

standings_dir = r"data/standings"
games_pages = [os.path.join(standings_dir, f) for f in os.listdir(standings_dir) if f.endswith(".html")]

In [76]:
games_df = pd.concat(games, ignore_index=True)

ValueError: No objects to concatenate

In [77]:
games_df

Empty DataFrame
Columns: []
Index: []

In [78]:
games_df['won'] = games_df['won'].astype(int)

KeyError: 'won'

In [79]:
games_df.to_csv("nba_games.csv")

In [80]:
player_games = []
base_cols = None
i = 0
for box_score in box_scores:
    try:
        home = 0
        soup = parse_html(box_score)

        line_score = read_line_score(soup)
        teams = list(line_score["team"])

        summaries = []
        for team in teams:
            opp = [t for t in teams if t != team][0]
            basic = read_player_stats(soup, team, "basic")
            advanced = read_player_stats(soup, team, "advanced")

            summary = pd.concat([basic.iloc[:-1, :], advanced.iloc[:-1, 1:]], axis=1)
            summary['team'] = team
            summary['home'] = home
            summary['opp_team'] = opp
            summary['total_team_points'] = line_score.loc[line_score['team']==team]['total'].values[0]
            summary['total_opp_points'] = line_score.loc[line_score['team']==opp]['total'].values[0]
            summary['won'] = summary['total_team_points'] > summary['total_opp_points']

            home += 1           
            summaries.append(summary)

        players = pd.concat(summaries)
        players.reset_index(inplace=True)
        players.rename(columns={'Starters': 'players'}, inplace=True)

        players['match_id'] = i
        
        players["date"] = os.path.basename(box_score)[:8]
        players["date"] = pd.to_datetime(players["date"], format="%Y%m%d")
        
        player_games.append(players)

        i += 1
        
        if len(games) % 100 == 0:
            print(f"{len(games)} / {len(box_scores)}")
    except:
        continue

In [81]:
player_games

[]

In [82]:
players_df = pd.concat(player_games)
players_df.reset_index(inplace=True)
players_df.drop(columns=['index'], inplace=True)
players_df

ValueError: No objects to concatenate

In [83]:
players_df.replace('Did Not Play', np.nan, inplace=True)
players_df.replace('Not With Team', np.nan, inplace=True)
players_df.replace('Player Suspended', np.nan, inplace=True)
players_df.replace('Did Not Dress', np.nan, inplace=True)

NameError: name 'players_df' is not defined

In [84]:
players_df['MP'].fillna('00:00', inplace=True)

NameError: name 'players_df' is not defined

In [ ]:
players_df[['Minutes', 'Seconds']] = players_df['MP'].str.split(':', expand=True)

# Convert minutes and seconds to seconds and sum them up
players_df['MP'] = pd.to_numeric(players_df['Minutes']) * 60 + pd.to_numeric(players_df['Seconds'])

# Drop the 'Minutes' and 'Seconds' columns if needed
players_df.drop(columns=['Minutes', 'Seconds'], inplace=True)
players_df.rename(columns={'MP': 'time(s)'}, inplace=True)

In [ ]:
players_df['won'] = players_df['won'].astype(int)

In [ ]:
new_types = {"FG" : float,
"FGA" : float,
"FG%" : float,
"3P" : float,
"3PA" : float,
"3P%" : float,
"FT" : float,
"FTA" : float,
"FT%" : float,
"ORB" : float,
"DRB" : float,
"TRB" : float,
"AST" : float,
"STL" : float,
"BLK" : float,
"TOV" : float,
"PF" : float,
"PTS" : float,
"+/-" : float,
"TS%" : float,
"eFG%" : float,
"3PAr" : float,
"FTr" : float,
"ORB%" : float,
"DRB%" : float,
"TRB%" : float,
"AST%" : float,
"STL%" : float,
"BLK%" : float,
"TOV%" : float,
"USG%" : float,
"ORtg" : float,
"DRtg" : float,
"BPM" : float,
"opp_team":str}

In [ ]:
new_column_order = [ 
 'match_id',
 'date', 'players',  'team',
 'time(s)',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 '+/-',
 'TS%',
 'eFG%',
 '3PAr',
 'FTr',
 'ORB%',
 'DRB%',
 'TRB%',
 'AST%',
 'STL%',
 'BLK%',
 'TOV%',
 'USG%',
 'ORtg',
 'DRtg',
 'BPM',
 'home',
 'opp_team',
 'total_team_points',
 'total_opp_points','won'
]

In [ ]:
players_df = players_df[new_column_order]

In [ ]:
players_df = players_df.astype(new_types)

In [ ]:
counting_stats = ['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS' ]

In [ ]:
players_df.loc[players_df['players'] == 'Lamar Stevens'][counting_stats]

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1416,2.0,2.0,1.000,1.0,1.0,1.000,0.0,0.0,NaN,2.0,0.0,2.0,0.0,0.0,0.0,3.0,1.0,5.0
1569,2.0,4.0,0.500,0.0,0.0,NaN,0.0,0.0,NaN,2.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,4.0
1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2520,0.0,1.0,0.000,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4143,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7515,1.0,3.0,0.333,0.0,2.0,0.000,2.0,2.0,1.000,0.0,1.0,1.0,1.0,1.0,1.0,0.0,3.0,4.0
7694,3.0,7.0,0.429,1.0,3.0,0.333,1.0,2.0,0.500,1.0,2.0,3.0,0.0,2.0,1.0,1.0,2.0,8.0
8168,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8866,1.0,1.0,1.000,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
9469,2.0,3.0,0.667,0.0,0.0,NaN,0.0,0.0,NaN,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,4.0
10197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10915,1.0,1.0,1.000,0.0,0.0,NaN,0.0,0.0,NaN,0.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0
11269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11735,2.0,4.0,0.500,0.0,1.0,0.000,0.0,0.0,NaN,1.0,4.0,5.0,0.0,1.0,1.0,1.0,1.0,4.0
12114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13059,1.0,6.0,0.167,0.0,0.0,NaN,3.0,4.0,0.750,1.0,3.0,4.0,0.0,0.0,1.0,0.0,2.0,5.0
13424,0.0,2.0,0.000,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14131,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
14478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15672,1.0,3.0,0.333,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,2.0
15986,3.0,4.0,0.750,0.0,0.0,NaN,2.0,3.0,0.667,3.0,2.0,5.0,1.0,0.0,0.0,1.0,0.0,8.0
16382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17607,2.0,4.0,0.500,1.0,1.0,1.000,0.0,0.0,NaN,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,5.0
18777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19229,5.0,10.0,0.500,0.0,1.0,0.000,0.0,0.0,NaN,1.0,6.0,7.0,0.0,0.0,2.0,2.0,3.0,10.0
19651,4.0,8.0,0.500,1.0,1.0,1.000,5.0,6.0,0.833,1.0,7.0,8.0,1.0,0.0,2.0,0.0,1.0,14.0
19831,6.0,10.0,0.600,1.0,1.0,1.000,0.0,3.0,0.000,0.0,5.0,5.0,1.0,1.0,0.0,3.0,1.0,13.0
20333,4.0,9.0,0.444,0.0,0.0,NaN,0.0,0.0,NaN,3.0,5.0,8.0,1.0,1.0,1.0,0.0,2.0,8.0
20881,8.0,9.0,0.889,1.0,1.0,1.000,0.0,0.0,NaN,2.0,4.0,6.0,2.0,0.0,1.0,1.0,0.0,17.0

In [ ]:
players_df.loc[(players_df['team'] == 'BOS') & (players_df['opp_team'] == 'PHI')]

,won,match_id,date,players,team,time(s),FG,FGA,FG%,3P,...,BLK%,TOV%,USG%,ORtg,DRtg,BPM,home,opp_team,total_team_points,total_opp_points
2967,0,108,2023-11-08,Derrick White,BOS,2254,6.0,18.0,0.333,3.0,...,2.1,9.2,25.0,98.0,107.0,2.2,0,PHI,103,106
2968,0,108,2023-11-08,Jayson Tatum,BOS,2225,6.0,14.0,0.429,2.0,...,0.0,11.5,20.1,104.0,96.0,6.6,0,PHI,103,106
2969,0,108,2023-11-08,Jaylen Brown,BOS,2132,4.0,13.0,0.308,2.0,...,2.2,22.4,21.7,63.0,111.0,-9.0,0,PHI,103,106
2970,0,108,2023-11-08,Jrue Holiday,BOS,2085,4.0,9.0,0.444,2.0,...,0.0,16.8,14.7,113.0,110.0,2.0,0,PHI,103,106
2971,0,108,2023-11-08,Kristaps Porziņģis,BOS,1864,10.0,19.0,0.526,2.0,...,2.5,0.0,31.2,138.0,113.0,12.6,0,PHI,103,106
2972,0,108,2023-11-08,Al Horford,BOS,1573,1.0,6.0,0.167,1.0,...,6.0,14.3,11.5,64.0,107.0,-3.2,0,PHI,103,106
2973,0,108,2023-11-08,Sam Hauser,BOS,1120,5.0,8.0,0.625,3.0,...,4.2,0.0,18.5,140.0,101.0,16.2,0,PHI,103,106
2974,0,108,2023-11-08,Payton Pritchard,BOS,961,0.0,4.0,0.000,0.0,...,0.0,20.0,13.5,63.0,117.0,-8.6,0,PHI,103,106
2975,0,108,2023-11-08,Luke Kornet,BOS,185,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,117.0,-7.8,0,PHI,103,106
2976,0,108,2023-11-08,Dalano Banton,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,PHI,103,106
2977,0,108,2023-11-08,Oshae Brissett,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,PHI,103,106
2978,0,108,2023-11-08,Svi Mykhailiuk,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,PHI,103,106
2979,0,108,2023-11-08,Lamar Stevens,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,PHI,103,106
3662,1,134,2023-11-15,Jayson Tatum,BOS,2310,10.0,23.0,0.435,4.0,...,0.0,10.5,33.9,120.0,117.0,5.8,0,PHI,117,107
3663,1,134,2023-11-15,Derrick White,BOS,2158,7.0,12.0,0.583,4.0,...,0.0,10.9,23.3,158.0,122.0,9.7,0,PHI,117,107
3664,1,134,2023-11-15,Jrue Holiday,BOS,2129,8.0,18.0,0.444,2.0,...,4.9,5.1,25.0,110.0,114.0,1.7,0,PHI,117,107
3665,1,134,2023-11-15,Sam Hauser,BOS,2113,3.0,9.0,0.333,2.0,...,2.5,0.0,11.6,114.0,125.0,-4.6,0,PHI,117,107
3666,1,134,2023-11-15,Al Horford,BOS,1729,5.0,9.0,0.556,4.0,...,15.1,0.0,14.2,170.0,109.0,16.7,0,PHI,117,107
3667,1,134,2023-11-15,Payton Pritchard,BOS,1395,2.0,5.0,0.400,1.0,...,0.0,0.0,9.8,140.0,126.0,-1.7,0,PHI,117,107
3668,1,134,2023-11-15,Luke Kornet,BOS,1148,4.0,4.0,1.000,0.0,...,0.0,29.1,16.4,137.0,116.0,3.0,0,PHI,117,107
3669,1,134,2023-11-15,Svi Mykhailiuk,BOS,920,2.0,4.0,0.500,1.0,...,0.0,20.0,14.9,106.0,119.0,-4.8,0,PHI,117,107
3670,1,134,2023-11-15,Dalano Banton,BOS,498,1.0,4.0,0.250,0.0,...,0.0,0.0,22.0,75.0,98.0,-10.3,0,PHI,117,107
3671,1,134,2023-11-15,Oshae Brissett,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,PHI,117,107
3672,1,134,2023-11-15,Neemias Queta,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,PHI,117,107
3673,1,134,2023-11-15,Lamar Stevens,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,PHI,117,107
5746,1,213,2023-12-01,Jaylen Brown,BOS,2108,8.0,20.0,0.400,1.0,...,4.6,12.1,30.0,86.0,110.0,-7.3,1,PHI,125,119
5747,1,213,2023-12-01,Jrue Holiday,BOS,2098,4.0,11.0,0.364,3.0,...,0.0,20.2,18.1,109.0,120.0,-3.2,1,PHI,125,119
5748,1,213,2023-12-01,Al Horford,BOS,1999,7.0,9.0,0.778,2.0,...,4.9,8.5,15.0,178.0,117.0,9.5,1,PHI,125,119
5749,1,213,2023-12-01,Derrick White,BOS,1923,5.0,11.0,0.455,3.0,...,2.5,6.4,20.6,157.0,118.0,7.2,1,PHI,125,119
5750,1,213,2023-12-01,Jayson Tatum,BOS,1647,6.0,9.0,0.667,2.0,...,3.0,35.1,30.9,107.0,113.0,1.7,1,PHI,125,119
5751,1,213,2023-12-01,Sam Hauser,BOS,1552,3.0,5.0,0.600,3.0,...,3.1,33.8,14.6,118.0,116.0,2.6,1,PHI,125,119
5752,1,213,2023-12-01,Payton Pritchard,BOS,1401,3.0,7.0,0.429,2.0,...,0.0,0.0,14.4,157.0,120.0,5.1,1,PHI,125,119
5753,1,213,2023-12-01,Neemias Queta,BOS,611,1.0,1.0,1.000,0.0,...,0.0,42.0,19.9,117.0,117.0,-6.1,1,PHI,125,119
5754,1,213,2023-12-01,Dalano Banton,BOS,604,2.0,4.0,0.500,0.0,...,8.1,0.0,18.8,132.0,116.0,2.7,1,PHI,125,119
5755,1,213,2023-12-01,Luke Kornet,BOS,455,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,123.0,-8.2,1,PHI,125,119
5756,1,213,2023-12-01,Oshae Brissett,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,PHI,125,119
5757,1,213,2023-12-01,Svi Mykhailiuk,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,PHI,125,119
5758,1,213,2023-12-01,Lamar Stevens,BOS,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,PHI,125,119

In [ ]:
players_df.to_csv("nba_games_players.csv")

NameError: name 'players_df' is not defined